### ISSUE TITLE
LayerParameter' object has no attribute 'source'

### ISSUE THREAD

**Issue by parul-123** [fanchenyou/deepdiary#2]
Hello, Chenyou Fan! When I am trying to train as per your instructions, I am getting error .

Traceback (most recent call last):
  File "finetune.py", line 397, in <module>

  File "finetune.py", line 214, in main
    #########################################
  File "finetune.py", line 57, in def_lstm_2_layer

  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 194, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 105, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 166, in _to_proto
    assign_proto(layer, k, v)
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 68, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: 'LayerParameter' object has no attribute 'source'

Could you help me with this?
I appreciate your help!

**Comment by fanchenyou** [comment]
Hi, can you paste the entire error message here?
Also, did you "make pycaffe" ?

**Comment by parul-123** [comment]
parsed parameters:
{
  "grad_clip": 5.0, 
  "dataset1": "coco", 
  "dataset2": "lifelog", 
  "solver": "rmsprop", 
  "snapshot_dir": "snapshot", 
  "batch_size": 32, 
  "word_count_threshold": 20, 
  "max_len": 30, 
  "save_model_as": "models/caffe_lstm_finetune_512_2_layer.p", 
  "num_layer": 2, 
  "deviceId": "0", 
  "lifelog_only": 0, 
  "hidden_size": 512
}
Initializing data provider for dataset coco...
BasicDataProvider: reading /home/himanshu/Documents/intern/deepdiary/examples/myexp/data/coco/dataset.json
BasicDataProvider: reading /home/himanshu/Documents/intern/deepdiary/examples/myexp/data/coco/vgg_feats.mat
Initializing data provider for dataset lifelog...
BasicDataProvider: reading /home/himanshu/Documents/intern/deepdiary/examples/myexp/data/lifelog/dataset.json
BasicDataProvider: reading /home/himanshu/Documents/intern/deepdiary/examples/myexp/data/lifelog/vgg_feats.mat
========= Vocabulary Exists in data/ folder
dataset coco
Size of train has 82783/414113 images/sentences
Size of val has 5000/25010 images/sentences
Size of test has 5000/25010 images/sentences
dataset lifelog
Size of train has 6620/25350 images/sentences
Size of val has 590/1780 images/sentences
Size of test has 0/0 images/sentences
Preparing HDF5 input files
/home/himanshu/Documents/intern/deepdiary/examples/myexp/h5_data/train_coco.h5 /home/himanshu/Documents/intern/deepdiary/examples/myexp/h5_data/test_coco.h5 Train/test H5 files already exist
Preparing HDF5 input files
/home/himanshu/Documents/intern/deepdiary/examples/myexp/h5_data/train_lifelog.h5 /home/himanshu/Documents/intern/deepdiary/examples/myexp/h5_data/test_lifelog.h5 Train/test H5 files already exist
Vocabulary Size 4528
('proto ', name: "img"
type: "HDF5Data"
top: "img"
top: "sent"
top: "pred"
)
('name ', 'source')
('val ', '/home/himanshu/Documents/intern/deepdiary/examples/myexp/h5_data/train_coco.txt')
Traceback (most recent call last):
  File "finetune.py", line 373, in <module>
    main(params)
  File "finetune.py", line 191, in main
    f.write(str(def_func(train_filename, hidden_size, batch_size, vocabulary_size, grad_clip, 1, max_len)))
  File "finetune.py", line 55, in def_lstm_2_layer
    return n.to_proto()
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 194, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 105, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 166, in _to_proto
    assign_proto(layer, k, v)
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 68, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: 'LayerParameter' object has no attribute 'source'


Also, I have done 'make pycaffe'

**Comment by parul-123** [comment]
parsed parameters:
{
  "grad_clip": 5.0, 
  "dataset1": "coco", 
  "dataset2": "lifelog", 
  "solver": "rmsprop", 
  "snapshot_dir": "snapshot", 
  "batch_size": 32, 
  "word_count_threshold": 20, 
  "max_len": 30, 
  "save_model_as": "models/caffe_lstm_finetune_512_2_layer.p", 
  "num_layer": 2, 
  "deviceId": "0", 
  "lifelog_only": 0, 
  "hidden_size": 512
}
Initializing data provider for dataset coco...
BasicDataProvider: reading /home/himanshu/Documents/intern/deepdiary/examples/myexp/data/coco/dataset.json
BasicDataProvider: reading /home/himanshu/Documents/intern/deepdiary/examples/myexp/data/coco/vgg_feats.mat
Initializing data provider for dataset lifelog...
BasicDataProvider: reading /home/himanshu/Documents/intern/deepdiary/examples/myexp/data/lifelog/dataset.json
BasicDataProvider: reading /home/himanshu/Documents/intern/deepdiary/examples/myexp/data/lifelog/vgg_feats.mat
preprocessing word counts and creating vocab based on word count threshold 20
filtered words from 23528 to 4526 in 1.63s
preprocessing word counts and creating vocab based on word count threshold 50
filtered words from 2059 to 476 in 0.09s
========= expand vocabulary from 4528
========= to 4548
dataset coco
Size of train has 82783/414113 images/sentences
Size of val has 5000/25010 images/sentences
Size of test has 5000/25010 images/sentences
dataset lifelog
Size of train has 6620/25350 images/sentences
Size of val has 590/1780 images/sentences
Size of test has 0/0 images/sentences
Preparing HDF5 input files
413763 (413763, 4096) (413763, 30) (413763, 31)
Dropped/Remained/Total 350/413763/414113

24998 (24998, 4096) (24998, 30) (24998, 31)
Dropped/Remained/Total 12/24998/25010
Preparing HDF5 input files
25010 (25010, 4096) (25010, 30) (25010, 31)
Dropped/Remained/Total 340/25010/25350
1770 (1770, 4096) (1770, 30) (1770, 31)
Dropped/Remained/Total 10/1770/1780

Vocabulary Size 4548
('proto ', name: "img"
type: "HDF5Data"
top: "img"
top: "sent"
top: "pred"
)
('name ', 'source')
('val ', '/home/himanshu/Documents/intern/deepdiary/examples/myexp/h5_data/train_coco.txt')
Traceback (most recent call last):
  File "finetune.py", line 373, in <module>
    main(params)
  File "finetune.py", line 191, in main
    f.write(str(def_func(train_filename, hidden_size, batch_size, vocabulary_size, grad_clip, 1, max_len)))
  File "finetune.py", line 55, in def_lstm_2_layer
    return n.to_proto()
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 194, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 105, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 166, in _to_proto
    assign_proto(layer, k, v)
  File "/home/himanshu/Documents/intern/deepdiary/python/caffe/net_spec.py", line 68, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: 'LayerParameter' object has no attribute 'source'

Also, I have done 'make pycaffe'

**Comment by parul-123** [comment]
I have resolved this issue by replacing "param_names = [s for s in dir(layer) if s.endswith('_param')]" with "param_names = [f.name for f in layer.DESCRIPTOR.fields if f.name.endswith('_param')]" in line 35 in file "net_spec.py" in caffe. It may be a caffe version issue.

**Comment by fanchenyou** [comment]
Hi Parul,
thanks for letting me know this !
Yeah, download this repository and not use master branch of caffe is the branch.

**Comment by yunhai0920** [comment]
Hello
I have also same problem ('LayerParameter' object has no attribute 'source' ). but I could not solve it. would you please guide me step by step. @parul-123

**Comment by fanchenyou** [comment]
Please git clone this and make && make pycaffe
